### ISSUE TITLE
No route to host after scripts of job

### ISSUE THREAD

**Issue by sanderjochems-whyellow** [cattle-ops/terraform-aws-gitlab-runner#1043]
# Describe the bug

After the scripts in the job have finished, the runner throws an error.

# To Reproduce

Sometimes I get a runner failure.

This is the error I'm getting at the end of the job. The scripts of the job have succeeded, but the job wasn't able to process the success result.

```log
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-4d1ca121 ...
WARNING: Failed to pull image with policy "always": error during connect: Post "https://10.0.48.179:2376/v1.41/images/create?fromImage=registry.gitlab.com%2Fgitlab-org%2Fgitlab-runner%2Fgitlab-runner-helper&tag=x86_64-4d1ca121": dial tcp 10.0.48.179:2376: connect: no route to host (manager.go:237:3s)
```

```log
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-4d1ca121 ...
WARNING: Failed to pull image with policy "always": Cannot connect to the Docker daemon at tcp://10.0.48.102:2376. Is the docker daemon running? (manager.go:237:0s)
ERROR: Job failed (system failure): Cannot connect to the Docker daemon at tcp://10.0.48.102:2376. Is the docker daemon running?
```

# Expected behavior

The success result of the job is passed to GitLab

# Additional context

I am using the latest version of the provider using the public network example.

**Comment by kayman-mk** [comment]
This article seems to be interesting: https://forum.gitlab.com/t/debug-credentials-from-root-docker-config-json-vs-credentials-from-payload-with-gitlab-runner-and-container-registry/87757

Could you share some details of your .gitlab-ci.yml and some more lines of the job output?

**Comment by kayman-mk** [comment]
There is a section at the bottom of [this page](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docke) describing the errors you encountered. Did you check this?

**Comment by sanderjochems-whyellow** [comment]
I have added the `docker:dind` service and the `DOCKER_HOST` variable in the terraform code for the runner worker. I'll send a new comment when I know more after some testing.

---

Below is the output of a job. This is just a sample, but more jobs are failing.

Job:
```yml
stages:
  - preparation
  - build
  - test
  - scan
  - publish

variables:
  WEB_DIR: "$CI_PROJECT_DIR/web"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"
  REACT_COMPONENTS_PROJECT_ID: "xxx"

image:
  name: public.ecr.aws/docker/library/node:lts-alpine

before_script:
  - cd $WEB_DIR

cache:
  key: web-npm
  paths:
    - $WEB_DIR/node_modules

web:npm:
  stage: preparation
  script:
    - npm config set ${CI_API_V4_URL#http*:}/projects/${REACT_COMPONENTS_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN}
    - npm config set @${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${REACT_COMPONENTS_PROJECT_ID}/packages/npm/
    - npm ci
```

Complete log:
```log
Running with gitlab-runner 15.8.2 (4d1ca121)
  on glrunner s[2](https://gitlab.com/<repo>/-/jobs/<project>#L2)LsxhJV, system ID: s_cd[3](https://gitlab.com/<repo>/-/jobs/<project>#L3)ed69122d5
Resolving secrets
00:00
Preparing the "docker+machine" executor
00:03
Using Docker executor with image public.ecr.aws/docker/library/node:lts-alpine ...
Pulling docker image public.ecr.aws/docker/library/node:lts-alpine ...
Using docker image sha256:3a617f[4](https://gitlab.com/<repo>/-/jobs/<project>#L4)39a70c99c88b4f6179a9c23bdc9ab21df2ad73[5](https://gitlab.com/<repo>/-/jobs/<project>#L5)4aae079c52caa5e3a7 for public.ecr.aws/docker/library/node:lts-alpine with digest public.ecr.aws/docker/library/node@sha25[6](https://gitlab.com/<repo>/-/jobs/<project>#L6):8e015de364a2eb2ed[7](https://gitlab.com/<repo>/-/jobs/<project>#L7)c52a558e9f716dcb615560ffd132234087c10ccc1f2c63 ...
Preparing environment
00:01
Running on runner-s2lsxhjv-project-41923800-concurrent-0 via runner-s2lsxhjv-glrunner-1700051085-f5e5e77b...
Getting source from Git repository
00:04
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/<repo>/.git/
Checking out 2279becd as refs/merge-requests/977/head...
Removing web/node_modules/
Skipping Git submodules setup
Restoring cache
00:10
Checking cache for web-npm-10-non_protected...
Downloading cache.zip from https://glrunner-301136870199-gitlab-runner-cache.s3.dualstack.eu-central-1.amazonaws.com/runner/s2LsxhJV/project/41923800/web-npm-10-non_protected 
Successfully extracted cache
Executing "step_script" stage of the job script
03:30
Using docker image sha256:3a617f439a70c99c88b4f6179a9c23bdc9ab21df2ad7354aae079c52caa5e3a7 for public.ecr.aws/docker/library/node:lts-alpine with digest public.ecr.aws/docker/library/node@sha256:8e015de364a2eb2ed7c52a558e9f716dcb615560ffd132234087c10ccc1f2c63 ...
$ cd $WEB_DIR
$ npm config set ${CI_API_V4_URL#http*:}/projects/${REACT_COMPONENTS_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN}
$ npm config set @${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${REACT_COMPONENTS_PROJECT_ID}/packages/npm/
$ npm ci
npm WARN deprecated subscriptions-transport-ws@0.9.1[8](https://gitlab.com/<repo>/-/jobs/<project>#L8): The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
added 1136 packages, and audited 1137 packages in 30s
258 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
$ npm run lint -- --no-fix
> web@0.0.0 lint
> eslint . --no-fix
Cleaning up project directory and file based variables
00:13
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-4d1ca121 ...
WARNING: Failed to pull image with policy "always": error during connect: Post "https://10.0.48.220:2376/v1.41/images/create?fromImage=registry.gitlab.com%2Fgitlab-org%2Fgitlab-runner%2Fgitlab-runner-helper&tag=x86_64-4d1ca121": dial tcp 10.0.48.220:2376: connect: no route to host (manager.go:237:3s)
ERROR: Job failed (system failure): error during connect: Post "https://10.0.48.220:2376/v1.41/containers/7a4cd71b8df1ae05271d55f1f0f86bab8[9](https://gitlab.com/<repo>/-/jobs/<project>#L9)b6ed60c39ae4920a7[10](https://gitlab.com/<repo>/-/jobs/<project>#L10)506a38e9d4d/wait?condition=not-running": dial tcp 10.0.48.2[20](https://gitlab.com/<repo>/-/jobs/<project>#L20):[23](https://gitlab.com/<repo>/-/jobs/<project>#L23)76: connect: no route to host
```
