### ISSUE TITLE
Fix formatting and docs during pre-commit?

### ISSUE THREAD

**Issue by kayman-mk** [cattle-ops/terraform-aws-gitlab-runner#423]
I always struggle with
- formatting the code prior to commit
- updating the Terraform docs before commit

I saw that pre-commit is used to verify that everything is ok. What about changing the files during the pre-commit automatically thus making life easier for developers?

**Comment by kayman-mk** [comment]
Format Terraform code: https://faun.pub/format-your-terraform-code-with-github-actions-2ce3ccdd6fb6

**Comment by kayman-mk** [comment]
Seems that it was already in place. Guess I didn't use pre-commit on my developer machine due to missing Python, argh. But I added support to format all files recursively.

**Comment by kayman-mk** [comment]
Seems that the docs are created in the `develop branch`. Can we do it for the formating as well?

**Comment by kayman-mk** [comment]
@npalm Shall we update the Github workflow to format the code as well? Found an action to do that:

```
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: my-terraform-config
```
